import { Injectable } from '@angular/core';
import { ResponseData } from '../models/responsedata.model';

/**
 * HeadersServices adds necessary headers to HTTP requests
 */
@Injectable({
  providedIn: 'root'
})
export class CleanerService {
  /**
   * clean removes elements from the array if the name is .DS_Store.
   * .DS_Store files are sometimes autogenerated in the assets/images
   * directory and can cause errors when trying to parse all files in
   * that directory.
   * If .DS_Store is specified in .gitignore, this is not needed
   * @param response The response data to clean
   */
  clean(response: ResponseData[]): ResponseData[] {
    return response.filter(elem => elem.name !== '.DS_Store');
  }

  /**
   * Inject necessary services
   */
  constructor() {}
}
